Module Font_Table
    Public Sub Font_Lesson_1()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "え"
        Puyo_Script.Letter(4) = "お"
        Puyo_Script.Letter(5) = "か"
        Puyo_Script.Letter(6) = "き"
        Puyo_Script.Letter(7) = "こ"

        Puyo_Script.Letter(8) = "そ"
        Puyo_Script.Letter(9) = "た"
        Puyo_Script.Letter(10) = "て"
        Puyo_Script.Letter(11) = "な"
        Puyo_Script.Letter(12) = "に"
        Puyo_Script.Letter(13) = "の"
        Puyo_Script.Letter(14) = "は"
        Puyo_Script.Letter(15) = "ふ"

        Puyo_Script.Letter(16) = "ま"
        Puyo_Script.Letter(17) = "も"
        Puyo_Script.Letter(18) = "ら"
        Puyo_Script.Letter(19) = "わ"
        Puyo_Script.Letter(20) = "ん"
        Puyo_Script.Letter(21) = "っ"
        Puyo_Script.Letter(22) = "だ"
        Puyo_Script.Letter(23) = "オ"

        Puyo_Script.Letter(24) = "ク"
        Puyo_Script.Letter(25) = "チ"
        Puyo_Script.Letter(26) = "ム"
        Puyo_Script.Letter(27) = "レ"
        Puyo_Script.Letter(28) = "ャ"
        Puyo_Script.Letter(29) = "「"
        Puyo_Script.Letter(30) = "」"
        Puyo_Script.Letter(31) = "。"

        Puyo_Script.Letter(32) = "、"
        Puyo_Script.Letter(33) = "！"
        Puyo_Script.Letter(34) = "茶"
        Puyo_Script.Letter(35) = "柱"
        Puyo_Script.Letter(36) = "勝"
        Puyo_Script.Letter(37) = "負"
        Puyo_Script.Letter(38) = "前"
        Puyo_Script.Letter(39) = "消"

        Puyo_Script.Letter(40) = "が"
        Puyo_Script.Letter(41) = "・"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Lesson_2()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "す"
        Puyo_Script.Letter(2) = "な"
        Puyo_Script.Letter(3) = "に"
        Puyo_Script.Letter(4) = "の"
        Puyo_Script.Letter(5) = "よ"
        Puyo_Script.Letter(6) = "わ"
        Puyo_Script.Letter(7) = "ん"

        Puyo_Script.Letter(8) = "っ"
        Puyo_Script.Letter(9) = "「"
        Puyo_Script.Letter(10) = "」"
        Puyo_Script.Letter(11) = "・"
        Puyo_Script.Letter(12) = "！"
        Puyo_Script.Letter(13) = "？"
        Puyo_Script.Letter(14) = "ー"
        Puyo_Script.Letter(15) = "何"

        Puyo_Script.Letter(16) = "■"
        Puyo_Script.Letter(17) = "■"
        Puyo_Script.Letter(18) = "■"
        Puyo_Script.Letter(19) = "■"
        Puyo_Script.Letter(20) = "■"
        Puyo_Script.Letter(21) = "■"
        Puyo_Script.Letter(22) = "■"
        Puyo_Script.Letter(23) = "■"

        Puyo_Script.Letter(24) = "■"
        Puyo_Script.Letter(25) = "■"
        Puyo_Script.Letter(26) = "■"
        Puyo_Script.Letter(27) = "■"
        Puyo_Script.Letter(28) = "■"
        Puyo_Script.Letter(29) = "■"
        Puyo_Script.Letter(30) = "■"
        Puyo_Script.Letter(31) = "■"

        Puyo_Script.Letter(32) = "■"
        Puyo_Script.Letter(33) = "■"
        Puyo_Script.Letter(34) = "■"
        Puyo_Script.Letter(35) = "■"
        Puyo_Script.Letter(36) = "■"
        Puyo_Script.Letter(37) = "■"
        Puyo_Script.Letter(38) = "■"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Lesson_3()
        Puyo_Script.Letter(0) = "　"
        Puyo_Script.Letter(1) = "、"
        Puyo_Script.Letter(2) = "・"
        Puyo_Script.Letter(3) = "？"
        Puyo_Script.Letter(4) = "！"
        Puyo_Script.Letter(5) = "ー"
        Puyo_Script.Letter(6) = "「"
        Puyo_Script.Letter(7) = "。"

        Puyo_Script.Letter(8) = "あ"
        Puyo_Script.Letter(9) = "い"
        Puyo_Script.Letter(10) = "う"
        Puyo_Script.Letter(11) = "え"
        Puyo_Script.Letter(12) = "お"
        Puyo_Script.Letter(13) = "が"
        Puyo_Script.Letter(14) = "け"
        Puyo_Script.Letter(15) = "さ"

        Puyo_Script.Letter(16) = "し"
        Puyo_Script.Letter(17) = "せ"
        Puyo_Script.Letter(18) = "た"
        Puyo_Script.Letter(19) = "だ"
        Puyo_Script.Letter(20) = "ち"
        Puyo_Script.Letter(21) = "て"
        Puyo_Script.Letter(22) = "で"
        Puyo_Script.Letter(23) = "な"

        Puyo_Script.Letter(24) = "に"
        Puyo_Script.Letter(25) = "の"
        Puyo_Script.Letter(26) = "ぷ"
        Puyo_Script.Letter(27) = "ほ"
        Puyo_Script.Letter(28) = "ま"
        Puyo_Script.Letter(29) = "め"
        Puyo_Script.Letter(30) = "ゃ"
        Puyo_Script.Letter(31) = "よ"

        Puyo_Script.Letter(32) = "わ"
        Puyo_Script.Letter(33) = "ん"
        Puyo_Script.Letter(34) = "中"
        Puyo_Script.Letter(35) = "■"
        Puyo_Script.Letter(36) = "■"
        Puyo_Script.Letter(37) = "■"
        Puyo_Script.Letter(38) = "■"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Lesson_End()
        Puyo_Script.Letter(0) = "、"
        Puyo_Script.Letter(1) = "。"
        Puyo_Script.Letter(2) = "・"
        Puyo_Script.Letter(3) = "々"
        Puyo_Script.Letter(4) = "あ"
        Puyo_Script.Letter(5) = "い"
        Puyo_Script.Letter(6) = "う"
        Puyo_Script.Letter(7) = "お"

        Puyo_Script.Letter(8) = "か"
        Puyo_Script.Letter(9) = "が"
        Puyo_Script.Letter(10) = "き"
        Puyo_Script.Letter(11) = "く"
        Puyo_Script.Letter(12) = "け"
        Puyo_Script.Letter(13) = "こ"
        Puyo_Script.Letter(14) = "さ"
        Puyo_Script.Letter(15) = "し"

        Puyo_Script.Letter(16) = "ず"
        Puyo_Script.Letter(17) = "ぞ"
        Puyo_Script.Letter(18) = "た"
        Puyo_Script.Letter(19) = "だ"
        Puyo_Script.Letter(20) = "っ"
        Puyo_Script.Letter(21) = "て"
        Puyo_Script.Letter(22) = "で"
        Puyo_Script.Letter(23) = "と"

        Puyo_Script.Letter(24) = "な"
        Puyo_Script.Letter(25) = "は"
        Puyo_Script.Letter(26) = "ば"
        Puyo_Script.Letter(27) = "ひ"
        Puyo_Script.Letter(28) = "び"
        Puyo_Script.Letter(29) = "ほ"
        Puyo_Script.Letter(30) = "ま"
        Puyo_Script.Letter(31) = "み"

        Puyo_Script.Letter(32) = "も"
        Puyo_Script.Letter(33) = "よ"
        Puyo_Script.Letter(34) = "る"
        Puyo_Script.Letter(35) = "ろ"
        Puyo_Script.Letter(36) = "を"
        Puyo_Script.Letter(37) = "何"
        Puyo_Script.Letter(38) = "強"
        Puyo_Script.Letter(39) = "私"

        Puyo_Script.Letter(40) = "少"
        Puyo_Script.Letter(41) = "倍"
        Puyo_Script.Letter(42) = "来"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_1()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "お"
        Puyo_Script.Letter(4) = "か"
        Puyo_Script.Letter(5) = "き"
        Puyo_Script.Letter(6) = "け"
        Puyo_Script.Letter(7) = "こ"

        Puyo_Script.Letter(8) = "さ"
        Puyo_Script.Letter(9) = "し"
        Puyo_Script.Letter(10) = "た"
        Puyo_Script.Letter(11) = "て"
        Puyo_Script.Letter(12) = "と"
        Puyo_Script.Letter(13) = "な"
        Puyo_Script.Letter(14) = "に"
        Puyo_Script.Letter(15) = "の"

        Puyo_Script.Letter(16) = "は"
        Puyo_Script.Letter(17) = "ふ"
        Puyo_Script.Letter(18) = "ま"
        Puyo_Script.Letter(19) = "も"
        Puyo_Script.Letter(20) = "よ"
        Puyo_Script.Letter(21) = "り"
        Puyo_Script.Letter(22) = "れ"
        Puyo_Script.Letter(23) = "を"

        Puyo_Script.Letter(24) = "ん"
        Puyo_Script.Letter(25) = "っ"
        Puyo_Script.Letter(26) = "ゃ"
        Puyo_Script.Letter(27) = "じ"
        Puyo_Script.Letter(28) = "ば"
        Puyo_Script.Letter(29) = "ぷ"
        Puyo_Script.Letter(30) = "コ"
        Puyo_Script.Letter(31) = "ス"

        Puyo_Script.Letter(32) = "テ"
        Puyo_Script.Letter(33) = "ト"
        Puyo_Script.Letter(34) = "ン"
        Puyo_Script.Letter(35) = "「"
        Puyo_Script.Letter(36) = "」"
        Puyo_Script.Letter(37) = "、"
        Puyo_Script.Letter(38) = "！"
        Puyo_Script.Letter(39) = "？"

        Puyo_Script.Letter(40) = "ー"
        Puyo_Script.Letter(41) = "前"
        Puyo_Script.Letter(42) = "通"
        Puyo_Script.Letter(43) = "勝"
        Puyo_Script.Letter(44) = "負"
        Puyo_Script.Letter(45) = "美"
        Puyo_Script.Letter(46) = "少"
        Puyo_Script.Letter(47) = "女"

        Puyo_Script.Letter(48) = "地"
        Puyo_Script.Letter(49) = "獄"
        Puyo_Script.Letter(50) = "・"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub


    Public Sub Font_Stage_2()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "し"
        Puyo_Script.Letter(2) = "す"
        Puyo_Script.Letter(3) = "の"
        Puyo_Script.Letter(4) = "は"
        Puyo_Script.Letter(5) = "ま"
        Puyo_Script.Letter(6) = "も"
        Puyo_Script.Letter(7) = "り"

        Puyo_Script.Letter(8) = "る"
        Puyo_Script.Letter(9) = "れ"
        Puyo_Script.Letter(10) = "を"
        Puyo_Script.Letter(11) = "っ"
        Puyo_Script.Letter(12) = "ゃ"
        Puyo_Script.Letter(13) = "じ"
        Puyo_Script.Letter(14) = "だ"
        Puyo_Script.Letter(15) = "「"

        Puyo_Script.Letter(16) = "」"
        Puyo_Script.Letter(17) = "、"
        Puyo_Script.Letter(18) = "・"
        Puyo_Script.Letter(19) = "！"
        Puyo_Script.Letter(20) = "？"
        Puyo_Script.Letter(21) = "ー"
        Puyo_Script.Letter(22) = "踊"
        Puyo_Script.Letter(23) = "奴"

        Puyo_Script.Letter(24) = "■"
        Puyo_Script.Letter(25) = "■"
        Puyo_Script.Letter(26) = "■"
        Puyo_Script.Letter(27) = "■"
        Puyo_Script.Letter(28) = "■"
        Puyo_Script.Letter(29) = "■"
        Puyo_Script.Letter(30) = "■"
        Puyo_Script.Letter(31) = "■"

        Puyo_Script.Letter(32) = "■"
        Puyo_Script.Letter(33) = "■"
        Puyo_Script.Letter(34) = "■"
        Puyo_Script.Letter(35) = "■"
        Puyo_Script.Letter(36) = "■"
        Puyo_Script.Letter(37) = "■"
        Puyo_Script.Letter(38) = "■"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_3()
        Puyo_Script.Letter(0) = "、"
        Puyo_Script.Letter(1) = "。"
        Puyo_Script.Letter(2) = "・"
        Puyo_Script.Letter(3) = "！"
        Puyo_Script.Letter(4) = "ー"
        Puyo_Script.Letter(5) = "「"
        Puyo_Script.Letter(6) = "」"
        Puyo_Script.Letter(7) = "う"

        Puyo_Script.Letter(8) = "え"
        Puyo_Script.Letter(9) = "お"
        Puyo_Script.Letter(10) = "か"
        Puyo_Script.Letter(11) = "が"
        Puyo_Script.Letter(12) = "き"
        Puyo_Script.Letter(13) = "く"
        Puyo_Script.Letter(14) = "こ"
        Puyo_Script.Letter(15) = "ぞ"

        Puyo_Script.Letter(16) = "た"
        Puyo_Script.Letter(17) = "っ"
        Puyo_Script.Letter(18) = "て"
        Puyo_Script.Letter(19) = "で"
        Puyo_Script.Letter(20) = "と"
        Puyo_Script.Letter(21) = "な"
        Puyo_Script.Letter(22) = "は"
        Puyo_Script.Letter(23) = "ふ"

        Puyo_Script.Letter(24) = "ぷ"
        Puyo_Script.Letter(25) = "よ"
        Puyo_Script.Letter(26) = "ら"
        Puyo_Script.Letter(27) = "わ"
        Puyo_Script.Letter(28) = "を"
        Puyo_Script.Letter(29) = "ん"
        Puyo_Script.Letter(30) = "キ"
        Puyo_Script.Letter(31) = "ク"

        Puyo_Script.Letter(32) = "ッ"
        Puyo_Script.Letter(33) = "言"
        Puyo_Script.Letter(34) = "三"
        Puyo_Script.Letter(35) = "十"
        Puyo_Script.Letter(36) = "勝"
        Puyo_Script.Letter(37) = "足"
        Puyo_Script.Letter(38) = "待"
        Puyo_Script.Letter(39) = "負"

        Puyo_Script.Letter(40) = "文"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_4()
        Puyo_Script.Letter(0) = "い"
        Puyo_Script.Letter(1) = "う"
        Puyo_Script.Letter(2) = "こ"
        Puyo_Script.Letter(3) = "し"
        Puyo_Script.Letter(4) = "て"
        Puyo_Script.Letter(5) = "と"
        Puyo_Script.Letter(6) = "な"
        Puyo_Script.Letter(7) = "は"

        Puyo_Script.Letter(8) = "も"
        Puyo_Script.Letter(9) = "よ"
        Puyo_Script.Letter(10) = "ら"
        Puyo_Script.Letter(11) = "る"
        Puyo_Script.Letter(12) = "を"
        Puyo_Script.Letter(13) = "ん"
        Puyo_Script.Letter(14) = "っ"
        Puyo_Script.Letter(15) = "で"

        Puyo_Script.Letter(16) = "「"
        Puyo_Script.Letter(17) = "」"
        Puyo_Script.Letter(18) = "、"
        Puyo_Script.Letter(19) = "！"
        Puyo_Script.Letter(20) = "場"
        Puyo_Script.Letter(21) = "合"
        Puyo_Script.Letter(22) = "通"
        Puyo_Script.Letter(23) = "■"

        Puyo_Script.Letter(24) = "■"
        Puyo_Script.Letter(25) = "■"
        Puyo_Script.Letter(26) = "■"
        Puyo_Script.Letter(27) = "■"
        Puyo_Script.Letter(28) = "■"
        Puyo_Script.Letter(29) = "■"
        Puyo_Script.Letter(30) = "■"
        Puyo_Script.Letter(31) = "■"

        Puyo_Script.Letter(32) = "■"
        Puyo_Script.Letter(33) = "■"
        Puyo_Script.Letter(34) = "■"
        Puyo_Script.Letter(35) = "■"
        Puyo_Script.Letter(36) = "■"
        Puyo_Script.Letter(37) = "■"
        Puyo_Script.Letter(38) = "■"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_5()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "き"
        Puyo_Script.Letter(4) = "く"
        Puyo_Script.Letter(5) = "さ"
        Puyo_Script.Letter(6) = "し"
        Puyo_Script.Letter(7) = "す"

        Puyo_Script.Letter(8) = "せ"
        Puyo_Script.Letter(9) = "た"
        Puyo_Script.Letter(10) = "て"
        Puyo_Script.Letter(11) = "な"
        Puyo_Script.Letter(12) = "に"
        Puyo_Script.Letter(13) = "の"
        Puyo_Script.Letter(14) = "は"
        Puyo_Script.Letter(15) = "ほ"

        Puyo_Script.Letter(16) = "ま"
        Puyo_Script.Letter(17) = "も"
        Puyo_Script.Letter(18) = "よ"
        Puyo_Script.Letter(19) = "る"
        Puyo_Script.Letter(20) = "ん"
        Puyo_Script.Letter(21) = "っ"
        Puyo_Script.Letter(22) = "ゅ"
        Puyo_Script.Letter(23) = "だ"

        Puyo_Script.Letter(24) = "ど"
        Puyo_Script.Letter(25) = "「"
        Puyo_Script.Letter(26) = "」"
        Puyo_Script.Letter(27) = "。"
        Puyo_Script.Letter(28) = "、"
        Puyo_Script.Letter(29) = "・"
        Puyo_Script.Letter(30) = "？"
        Puyo_Script.Letter(31) = "ー"

        Puyo_Script.Letter(32) = "サ"
        Puyo_Script.Letter(33) = "ソ"
        Puyo_Script.Letter(34) = "マ"
        Puyo_Script.Letter(35) = "リ"
        Puyo_Script.Letter(36) = "ン"
        Puyo_Script.Letter(37) = "相"
        Puyo_Script.Letter(38) = "手"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_6()
        Puyo_Script.Letter(0) = "　"
        Puyo_Script.Letter(1) = "、"
        Puyo_Script.Letter(2) = "？"
        Puyo_Script.Letter(3) = "！"
        Puyo_Script.Letter(4) = "ー"
        Puyo_Script.Letter(5) = "「"
        Puyo_Script.Letter(6) = "。"
        Puyo_Script.Letter(7) = "あ"

        Puyo_Script.Letter(8) = "ぃ"
        Puyo_Script.Letter(9) = "い"
        Puyo_Script.Letter(10) = "う"
        Puyo_Script.Letter(11) = "ぉ"
        Puyo_Script.Letter(12) = "お"
        Puyo_Script.Letter(13) = "く"
        Puyo_Script.Letter(14) = "け"
        Puyo_Script.Letter(15) = "こ"

        Puyo_Script.Letter(16) = "さ"
        Puyo_Script.Letter(17) = "し"
        Puyo_Script.Letter(18) = "せ"
        Puyo_Script.Letter(19) = "そ"
        Puyo_Script.Letter(20) = "だ"
        Puyo_Script.Letter(21) = "ち"
        Puyo_Script.Letter(22) = "っ"
        Puyo_Script.Letter(23) = "て"

        Puyo_Script.Letter(24) = "で"
        Puyo_Script.Letter(25) = "と"
        Puyo_Script.Letter(26) = "ど"
        Puyo_Script.Letter(27) = "な"
        Puyo_Script.Letter(28) = "の"
        Puyo_Script.Letter(29) = "は"
        Puyo_Script.Letter(30) = "ぼ"
        Puyo_Script.Letter(31) = "も"

        Puyo_Script.Letter(32) = "ゃ"
        Puyo_Script.Letter(33) = "ゆ"
        Puyo_Script.Letter(34) = "よ"
        Puyo_Script.Letter(35) = "ら"
        Puyo_Script.Letter(36) = "る"
        Puyo_Script.Letter(37) = "ろ"
        Puyo_Script.Letter(38) = "ん"
        Puyo_Script.Letter(39) = "耳"

        Puyo_Script.Letter(40) = "失"
        Puyo_Script.Letter(41) = "受"
        Puyo_Script.Letter(42) = "勝"
        Puyo_Script.Letter(43) = "知"
        Puyo_Script.Letter(44) = "笛"
        Puyo_Script.Letter(45) = "負"
        Puyo_Script.Letter(46) = "礼"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_7()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "え"
        Puyo_Script.Letter(4) = "か"
        Puyo_Script.Letter(5) = "く"
        Puyo_Script.Letter(6) = "こ"
        Puyo_Script.Letter(7) = "さ"

        Puyo_Script.Letter(8) = "な"
        Puyo_Script.Letter(9) = "の"
        Puyo_Script.Letter(10) = "は"
        Puyo_Script.Letter(11) = "ら"
        Puyo_Script.Letter(12) = "わ"
        Puyo_Script.Letter(13) = "っ"
        Puyo_Script.Letter(14) = "げ"
        Puyo_Script.Letter(15) = "「"

        Puyo_Script.Letter(16) = "」"
        Puyo_Script.Letter(17) = "・"
        Puyo_Script.Letter(18) = "！"
        Puyo_Script.Letter(19) = "臭"
        Puyo_Script.Letter(20) = "先"
        Puyo_Script.Letter(21) = "通"
        Puyo_Script.Letter(22) = "■"
        Puyo_Script.Letter(23) = "■"

        Puyo_Script.Letter(24) = "■"
        Puyo_Script.Letter(25) = "■"
        Puyo_Script.Letter(26) = "■"
        Puyo_Script.Letter(27) = "■"
        Puyo_Script.Letter(28) = "■"
        Puyo_Script.Letter(29) = "■"
        Puyo_Script.Letter(30) = "■"
        Puyo_Script.Letter(31) = "■"

        Puyo_Script.Letter(32) = "■"
        Puyo_Script.Letter(33) = "■"
        Puyo_Script.Letter(34) = "■"
        Puyo_Script.Letter(35) = "■"
        Puyo_Script.Letter(36) = "■"
        Puyo_Script.Letter(37) = "■"
        Puyo_Script.Letter(38) = "■"
        Puyo_Script.Letter(39) = "■"

        Puyo_Script.Letter(40) = "■"
        Puyo_Script.Letter(41) = "■"
        Puyo_Script.Letter(42) = "■"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_8()
        Puyo_Script.Letter(0) = "い"
        Puyo_Script.Letter(1) = "う"
        Puyo_Script.Letter(2) = "お"
        Puyo_Script.Letter(3) = "か"
        Puyo_Script.Letter(4) = "く"
        Puyo_Script.Letter(5) = "こ"
        Puyo_Script.Letter(6) = "さ"
        Puyo_Script.Letter(7) = "し"

        Puyo_Script.Letter(8) = "そ"
        Puyo_Script.Letter(9) = "た"
        Puyo_Script.Letter(10) = "て"
        Puyo_Script.Letter(11) = "と"
        Puyo_Script.Letter(12) = "な"
        Puyo_Script.Letter(13) = "に"
        Puyo_Script.Letter(14) = "の"
        Puyo_Script.Letter(15) = "は"

        Puyo_Script.Letter(16) = "へ"
        Puyo_Script.Letter(17) = "ほ"
        Puyo_Script.Letter(18) = "ま"
        Puyo_Script.Letter(19) = "や"
        Puyo_Script.Letter(20) = "よ"
        Puyo_Script.Letter(21) = "り"
        Puyo_Script.Letter(22) = "る"
        Puyo_Script.Letter(23) = "れ"

        Puyo_Script.Letter(24) = "ろ"
        Puyo_Script.Letter(25) = "わ"
        Puyo_Script.Letter(26) = "ん"
        Puyo_Script.Letter(27) = "っ"
        Puyo_Script.Letter(28) = "ょ"
        Puyo_Script.Letter(29) = "が"
        Puyo_Script.Letter(30) = "だ"
        Puyo_Script.Letter(31) = "で"

        Puyo_Script.Letter(32) = "ば"
        Puyo_Script.Letter(33) = "ぼ"
        Puyo_Script.Letter(34) = "「"
        Puyo_Script.Letter(35) = "」"
        Puyo_Script.Letter(36) = "。"
        Puyo_Script.Letter(37) = "、"
        Puyo_Script.Letter(38) = "！"
        Puyo_Script.Letter(39) = "ー"

        Puyo_Script.Letter(40) = "勝"
        Puyo_Script.Letter(41) = "手"
        Puyo_Script.Letter(42) = "相"
        Puyo_Script.Letter(43) = "■"
        Puyo_Script.Letter(44) = "■"
        Puyo_Script.Letter(45) = "■"
        Puyo_Script.Letter(46) = "■"
        Puyo_Script.Letter(47) = "■"

        Puyo_Script.Letter(48) = "■"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_9()
        Puyo_Script.Letter(0) = "い"
        Puyo_Script.Letter(1) = "う"
        Puyo_Script.Letter(2) = "お"
        Puyo_Script.Letter(3) = "き"
        Puyo_Script.Letter(4) = "け"
        Puyo_Script.Letter(5) = "こ"
        Puyo_Script.Letter(6) = "さ"
        Puyo_Script.Letter(7) = "し"

        Puyo_Script.Letter(8) = "す"
        Puyo_Script.Letter(9) = "ち"
        Puyo_Script.Letter(10) = "て"
        Puyo_Script.Letter(11) = "と"
        Puyo_Script.Letter(12) = "な"
        Puyo_Script.Letter(13) = "に"
        Puyo_Script.Letter(14) = "ね"
        Puyo_Script.Letter(15) = "の"

        Puyo_Script.Letter(16) = "は"
        Puyo_Script.Letter(17) = "も"
        Puyo_Script.Letter(18) = "よ"
        Puyo_Script.Letter(19) = "り"
        Puyo_Script.Letter(20) = "る"
        Puyo_Script.Letter(21) = "ろ"
        Puyo_Script.Letter(22) = "わ"
        Puyo_Script.Letter(23) = "を"

        Puyo_Script.Letter(24) = "ん"
        Puyo_Script.Letter(25) = "っ"
        Puyo_Script.Letter(26) = "ょ"
        Puyo_Script.Letter(27) = "が"
        Puyo_Script.Letter(28) = "ぞ"
        Puyo_Script.Letter(29) = "ど"
        Puyo_Script.Letter(30) = "だ"
        Puyo_Script.Letter(31) = "ど"

        Puyo_Script.Letter(32) = "ば"
        Puyo_Script.Letter(33) = "「"
        Puyo_Script.Letter(34) = "」"
        Puyo_Script.Letter(35) = "。"
        Puyo_Script.Letter(36) = "、"
        Puyo_Script.Letter(37) = "・"
        Puyo_Script.Letter(38) = "！"
        Puyo_Script.Letter(39) = "イ"

        Puyo_Script.Letter(40) = "ケ"
        Puyo_Script.Letter(41) = "チ"
        Puyo_Script.Letter(42) = "ン"
        Puyo_Script.Letter(43) = "ド"
        Puyo_Script.Letter(44) = "通"
        Puyo_Script.Letter(45) = "欲"
        Puyo_Script.Letter(46) = "俺"
        Puyo_Script.Letter(47) = "様"

        Puyo_Script.Letter(48) = "場"
        Puyo_Script.Letter(49) = "所"
        Puyo_Script.Letter(50) = "許"
        Puyo_Script.Letter(51) = "人"
        Puyo_Script.Letter(52) = "怒"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_10()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "え"
        Puyo_Script.Letter(4) = "お"
        Puyo_Script.Letter(5) = "か"
        Puyo_Script.Letter(6) = "く"
        Puyo_Script.Letter(7) = "け"

        Puyo_Script.Letter(8) = "こ"
        Puyo_Script.Letter(9) = "し"
        Puyo_Script.Letter(10) = "そ"
        Puyo_Script.Letter(11) = "た"
        Puyo_Script.Letter(12) = "て"
        Puyo_Script.Letter(13) = "と"
        Puyo_Script.Letter(14) = "な"
        Puyo_Script.Letter(15) = "に"

        Puyo_Script.Letter(16) = "の"
        Puyo_Script.Letter(17) = "は"
        Puyo_Script.Letter(18) = "ま"
        Puyo_Script.Letter(19) = "も"
        Puyo_Script.Letter(20) = "や"
        Puyo_Script.Letter(21) = "ゆ"
        Puyo_Script.Letter(22) = "よ"
        Puyo_Script.Letter(23) = "る"

        Puyo_Script.Letter(24) = "を"
        Puyo_Script.Letter(25) = "ん"
        Puyo_Script.Letter(26) = "っ"
        Puyo_Script.Letter(27) = "が"
        Puyo_Script.Letter(28) = "げ"
        Puyo_Script.Letter(29) = "ぞ"
        Puyo_Script.Letter(30) = "だ"
        Puyo_Script.Letter(31) = "ぷ"

        Puyo_Script.Letter(32) = "「"
        Puyo_Script.Letter(33) = "」"
        Puyo_Script.Letter(34) = "。"
        Puyo_Script.Letter(35) = "、"
        Puyo_Script.Letter(36) = "・"
        Puyo_Script.Letter(37) = "！"
        Puyo_Script.Letter(38) = "？"
        Puyo_Script.Letter(39) = "ウ"

        Puyo_Script.Letter(40) = "シ"
        Puyo_Script.Letter(41) = "ィ"
        Puyo_Script.Letter(42) = "ェ"
        Puyo_Script.Letter(43) = "グ"
        Puyo_Script.Letter(44) = "ゾ"
        Puyo_Script.Letter(45) = "前"
        Puyo_Script.Letter(46) = "欲"
        Puyo_Script.Letter(47) = "力"

        Puyo_Script.Letter(48) = "魔"
        Puyo_Script.Letter(49) = "吸"
        Puyo_Script.Letter(50) = "収"
        Puyo_Script.Letter(51) = "闇"
        Puyo_Script.Letter(52) = "導"
        Puyo_Script.Letter(53) = "師"
        Puyo_Script.Letter(54) = "様"
        Puyo_Script.Letter(55) = "地"

        Puyo_Script.Letter(56) = "獄"
        Puyo_Script.Letter(57) = "王"
        Puyo_Script.Letter(58) = "者"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_11()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "お"
        Puyo_Script.Letter(4) = "こ"
        Puyo_Script.Letter(5) = "し"
        Puyo_Script.Letter(6) = "す"
        Puyo_Script.Letter(7) = "そ"

        Puyo_Script.Letter(8) = "た"
        Puyo_Script.Letter(9) = "ち"
        Puyo_Script.Letter(10) = "と"
        Puyo_Script.Letter(11) = "な"
        Puyo_Script.Letter(12) = "に"
        Puyo_Script.Letter(13) = "ぬ"
        Puyo_Script.Letter(14) = "ね"
        Puyo_Script.Letter(15) = "の"

        Puyo_Script.Letter(16) = "よ"
        Puyo_Script.Letter(17) = "り"
        Puyo_Script.Letter(18) = "わ"
        Puyo_Script.Letter(19) = "ん"
        Puyo_Script.Letter(20) = "っ"
        Puyo_Script.Letter(21) = "ゃ"
        Puyo_Script.Letter(22) = "ょ"
        Puyo_Script.Letter(23) = "じ"

        Puyo_Script.Letter(24) = "だ"
        Puyo_Script.Letter(25) = "で"
        Puyo_Script.Letter(26) = "ぷ"
        Puyo_Script.Letter(27) = "「"
        Puyo_Script.Letter(28) = "」"
        Puyo_Script.Letter(29) = "、"
        Puyo_Script.Letter(30) = "！"
        Puyo_Script.Letter(31) = "？"

        Puyo_Script.Letter(32) = "ー"
        Puyo_Script.Letter(33) = "ウ"
        Puyo_Script.Letter(34) = "ス"
        Puyo_Script.Letter(35) = "タ"
        Puyo_Script.Letter(36) = "ノ"
        Puyo_Script.Letter(37) = "ミ"
        Puyo_Script.Letter(38) = "ル"
        Puyo_Script.Letter(39) = "ロ"

        Puyo_Script.Letter(40) = "危"
        Puyo_Script.Letter(41) = "様"
        Puyo_Script.Letter(42) = "命"
        Puyo_Script.Letter(43) = "令"
        Puyo_Script.Letter(44) = "待"
        Puyo_Script.Letter(45) = "地"
        Puyo_Script.Letter(46) = "獄"
        Puyo_Script.Letter(47) = "戦"

        Puyo_Script.Letter(48) = "れ"
        Puyo_Script.Letter(49) = "■"
        Puyo_Script.Letter(50) = "■"
        Puyo_Script.Letter(51) = "■"
        Puyo_Script.Letter(52) = "■"
        Puyo_Script.Letter(53) = "■"
        Puyo_Script.Letter(54) = "■"
        Puyo_Script.Letter(55) = "■"

        Puyo_Script.Letter(56) = "■"
        Puyo_Script.Letter(57) = "■"
        Puyo_Script.Letter(58) = "■"
        Puyo_Script.Letter(59) = "■"
        Puyo_Script.Letter(60) = "■"
        Puyo_Script.Letter(61) = "■"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_12()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "お"
        Puyo_Script.Letter(3) = "か"
        Puyo_Script.Letter(4) = "き"
        Puyo_Script.Letter(5) = "く"
        Puyo_Script.Letter(6) = "け"
        Puyo_Script.Letter(7) = "こ"

        Puyo_Script.Letter(8) = "さ"
        Puyo_Script.Letter(9) = "し"
        Puyo_Script.Letter(10) = "す"
        Puyo_Script.Letter(11) = "せ"
        Puyo_Script.Letter(12) = "た"
        Puyo_Script.Letter(13) = "て"
        Puyo_Script.Letter(14) = "と"
        Puyo_Script.Letter(15) = "な"

        Puyo_Script.Letter(16) = "に"
        Puyo_Script.Letter(17) = "ね"
        Puyo_Script.Letter(18) = "の"
        Puyo_Script.Letter(19) = "は"
        Puyo_Script.Letter(20) = "へ"
        Puyo_Script.Letter(21) = "め"
        Puyo_Script.Letter(22) = "も"
        Puyo_Script.Letter(23) = "ゆ"

        Puyo_Script.Letter(24) = "よ"
        Puyo_Script.Letter(25) = "ら"
        Puyo_Script.Letter(26) = "り"
        Puyo_Script.Letter(27) = "る"
        Puyo_Script.Letter(28) = "れ"
        Puyo_Script.Letter(29) = "わ"
        Puyo_Script.Letter(30) = "を"
        Puyo_Script.Letter(31) = "っ"

        Puyo_Script.Letter(32) = "が"
        Puyo_Script.Letter(33) = "ば"
        Puyo_Script.Letter(34) = "ば"
        Puyo_Script.Letter(35) = "「"
        Puyo_Script.Letter(36) = "」"
        Puyo_Script.Letter(37) = "。"
        Puyo_Script.Letter(38) = "、"
        Puyo_Script.Letter(39) = "・"

        Puyo_Script.Letter(40) = "！"
        Puyo_Script.Letter(41) = "？"
        Puyo_Script.Letter(42) = "ー"
        Puyo_Script.Letter(43) = "サ"
        Puyo_Script.Letter(44) = "タ"
        Puyo_Script.Letter(45) = "ム"
        Puyo_Script.Letter(46) = "ル"
        Puyo_Script.Letter(47) = "ン"

        Puyo_Script.Letter(48) = "ッ"
        Puyo_Script.Letter(49) = "グ"
        Puyo_Script.Letter(50) = "様"
        Puyo_Script.Letter(51) = "帰"
        Puyo_Script.Letter(52) = "先"
        Puyo_Script.Letter(53) = "行"
        Puyo_Script.Letter(54) = "結"
        Puyo_Script.Letter(55) = "婚"

        Puyo_Script.Letter(56) = "問"
        Puyo_Script.Letter(57) = "答"
        Puyo_Script.Letter(58) = "無"
        Puyo_Script.Letter(59) = "用"
        Puyo_Script.Letter(60) = "会"
        Puyo_Script.Letter(61) = "倒"
        Puyo_Script.Letter(62) = "■"
        Puyo_Script.Letter(63) = "■"
    End Sub
    Public Sub Font_Stage_13()
        Puyo_Script.Letter(0) = "あ"
        Puyo_Script.Letter(1) = "い"
        Puyo_Script.Letter(2) = "う"
        Puyo_Script.Letter(3) = "え"
        Puyo_Script.Letter(4) = "お"
        Puyo_Script.Letter(5) = "か"
        Puyo_Script.Letter(6) = "け"
        Puyo_Script.Letter(7) = "こ"

        Puyo_Script.Letter(8) = "さ"
        Puyo_Script.Letter(9) = "す"
        Puyo_Script.Letter(10) = "そ"
        Puyo_Script.Letter(11) = "た"
        Puyo_Script.Letter(12) = "ち"
        Puyo_Script.Letter(13) = "て"
        Puyo_Script.Letter(14) = "と"
        Puyo_Script.Letter(15) = "な"

        Puyo_Script.Letter(16) = "に"
        Puyo_Script.Letter(17) = "ぬ"
        Puyo_Script.Letter(18) = "ね"
        Puyo_Script.Letter(19) = "の"
        Puyo_Script.Letter(20) = "は"
        Puyo_Script.Letter(21) = "ほ"
        Puyo_Script.Letter(22) = "ま"
        Puyo_Script.Letter(23) = "む"

        Puyo_Script.Letter(24) = "や"
        Puyo_Script.Letter(25) = "よ"
        Puyo_Script.Letter(26) = "り"
        Puyo_Script.Letter(27) = "ろ"
        Puyo_Script.Letter(28) = "を"
        Puyo_Script.Letter(29) = "ん"
        Puyo_Script.Letter(30) = "っ"
        Puyo_Script.Letter(31) = "が"

        Puyo_Script.Letter(32) = "だ"
        Puyo_Script.Letter(33) = "で"
        Puyo_Script.Letter(34) = "ぱ"
        Puyo_Script.Letter(35) = "ぷ"
        Puyo_Script.Letter(36) = "・"
        Puyo_Script.Letter(37) = "」"
        Puyo_Script.Letter(38) = "。"
        Puyo_Script.Letter(39) = "、"

        Puyo_Script.Letter(40) = "！"
        Puyo_Script.Letter(41) = "？"
        Puyo_Script.Letter(42) = "ー"
        Puyo_Script.Letter(43) = "サ"
        Puyo_Script.Letter(44) = "セ"
        Puyo_Script.Letter(45) = "タ"
        Puyo_Script.Letter(46) = "フ"
        Puyo_Script.Letter(47) = "リ"

        Puyo_Script.Letter(48) = "ン"
        Puyo_Script.Letter(49) = "私"
        Puyo_Script.Letter(50) = "仕"
        Puyo_Script.Letter(51) = "掛"
        Puyo_Script.Letter(52) = "罠"
        Puyo_Script.Letter(53) = "耐"
        Puyo_Script.Letter(54) = "来"
        Puyo_Script.Letter(55) = "地"

        Puyo_Script.Letter(56) = "獄"
        Puyo_Script.Letter(57) = "趣"
        Puyo_Script.Letter(58) = "味"
        Puyo_Script.Letter(59) = "最"
        Puyo_Script.Letter(60) = "新"
        Puyo_Script.Letter(61) = "強"
        Puyo_Script.Letter(62) = "埋"
        Puyo_Script.Letter(63) = "朽"
    End Sub
End Module
